### ISSUE TITLE
グループ検索が動作不良？

### ISSUE THREAD

**Issue by yamamoto-ryuzo** [yamamoto-ryuzo/GEO-search-plugin#2]
@ageno-geo 
画面的にはタブが増えますが，実際に検索するとトップのタブの検索を実施しているようです。
確認ください。
実際にはマルコポーロタブが対象になっている。
![image](https://github.com/yamamoto-ryuzo/GEO-search-plugin/assets/86514652/a7764f79-e60c-4769-b3cb-933c3167f8ba)

**Comment by soja-suidou** [comment]
@ageno-geo
修正後も動作不良です。

**Comment by ageno-geo** [comment]
すみません、確認します

**Comment by soja-suidou** [comment]
マニュアル：
<html>
<body>


Group | タブをまとめるタブグループ、グループ名となり同名グループでまとまる。 | str
-- | -- | --



</body>
</html>
PY:
<html>
<body>


group | タブをまとめるタブグループ、グループ名となり同名グループでまとまる。 | str
-- | -- | --



</body>
</html>

このあたりが検索結果のエラーに影響しているのでしょうか。
要するに、本当にこの設定しかないのですね・・・・
他のご作法があるのかと思っていました。

相変わらず、先頭のタブしか検索してくれません。

**Comment by yamamoto-ryuzo** [comment]
動作確認しました。
OKです。
